### ISSUE TITLE
Hole for connector to wrist strap

### ISSUE THREAD

**Issue by PowerPress** [BusKill/usb-a-magnetic-breakaway#3]
It would be nice if there were decent sized hole so you could have a connector in the hole and a wrist strap attached to the connector around your wrist. So it would be easy to jerk your wrist away if you wanted to trigger the device without having to reach  for it. Essentially the laptop would be leashed to the user if the user desired in case a thief just grabbed it and tried running it would require no involvement on the user to enable the protection mechanism.

https://www.bhphotovideo.com/c/product/601276-REG/Olympus_202316_Adjustable_Wrist_Strap_Water.html/?ap=y&ap=y&smp=y&smp=y&lsft=BI%3A514&gclid=CjwKCAiA8Jf-BRB-EiwAWDtEGtiX9QbtGaC5SUQNPmRGUbcYbcHtJce654DOlE8Isrk7GvSu4qJoLRoCxuMQAvD_BwE

**Comment by maltfield** [comment]
BusKill is already designed to connect to the body at the hip. I think the only thing a wrist connection would change is increase the false-positive rate.

 * https://docs.buskill.in/buskill-app/en/stable/introduction/quickstart.html
