### ISSUE TITLE
Supplier Research (no 3D printing)

### ISSUE THREAD

**Issue by maltfield** [BusKill/usb-a-magnetic-breakaway#4]
This issue will track my attempts to find a supplier to manufacturer the USB-A Magnetic Breakaway component.

This will happen in parallel as we continue with efforts on the ideal solution, which is a totally open-source, 3D-printable shell that can be built easily, low-tech, with COTS components.

 * https://github.com/BusKill/usb-a-magnetic-breakaway/issues/2

But we can't let perfect be the enemy of the good, and as I write this there's many non-techie journalists, sources, activists, etc that could benefit from having a pre-assembled BusKill cable available for purchase. To fast-track that end-goal, I'll try to find a supplier who can make this component for us -- or supply us with the components sufficient for us to make it ourselves with non-trivial manufacturing required on our end.

**Comment by maltfield** [comment]
I've only ever found one supplier of a USB-A magnetic breakway: Griffin Technology. This is what I used to build my original BusKill cable, and--well--they totally sold-out on Amazon after I linked-to them in my original article describing how to build a BusKill cable:

 * https://tech.michaelaltfield.net/2020/01/02/buskill-laptop-kill-cord-dead-man-switch/

3 weeks ago I contacted Griffin's Sales Manager for Retail & Distribution in Europe (triccardi _at_ incipio.com), and he informed me that they EOL'd their magnetic breakaway adapters--both in USB-C and USB-A. I asked what would be required to jumpstart production, but I got no response.

**Comment by maltfield** [comment]
I tried last week to signup for an alibaba account, but I kept getting this error

```
The mobile number or email address is blacklisted
```

It wasn't at all clear if the issue was my email address or phone number. I tried several. Eventually I got it to work with an old gmail account that I fortunately still have access to.

After I logged-in I tried to change to my real email address again, but it wouldn't work. I opened a support chat and quickly was told that they ban any email addresses with `alibaba` in their name. Well, that breaks my email address naming convention, but I found that using `babaali` worked fine :shrug:

**Comment by maltfield** [comment]
I found several vendors of interest. For this first round, I decided to contact three vendors that all manufacture exactly what we need, but with USB-C.

 1. Shenzhen Bvanki Technology Co., Ltd.  https://www.alibaba.com/product-detail/2020-Non-magnetic-to-Magnetic-Adapter_62510448064.html

 1. Shenzhen EONLINE Industrial Co., Ltd. https://www.alibaba.com/product-detail/Eonline-3A-Type-C-Adapter-Magnetic_1600096650403.html?spm=a2700.8267363.selected.1.54b93e5fI1rRxA

 1. Sichuan Mandick Import And Export Trade Co., Ltd. https://mandick.en.alibaba.com/?spm=a2700.wholesale.cordpanyb.2.92f23cf8bBQCTf

```
Hi,

Is it possible for you to make a Magnetic Breakaway for USB type A (standard USB)?

 * <link to their product>

The item above is similar to what I'd need, except I want the male end to be a USB-A male end and the female end to be a USB-A female end.

Please let me know if you have this item available in USB type-A (standard USB, not USB-C) only.


Thank you,
Michael
```

**Comment by maltfield** [comment]
All 3x suppliers said they don't make usb magnetic breakaways for USB-A.

I followed-up with a request to make a customized order, but I think these vendors all specialize in accessories for mobile phones, which is the market for these USB-C adapters and they don't do USB-A.

**Comment by maltfield** [comment]
I messaged another 8 vendors, all appeared from the first page when searching for "usb pogo pin magnetic pdb" on alibaba

1. Shenzhen QH Industrial Co., Ltd. https://mold-parts.en.alibaba.com/product/1600237806652-826886905/Professional_Magnetic_USB_A_to_micro_USA_Cable_Connector_Male_Female_Pogo_Pin_Connector.html
2. Shenzhen Like Hardware Electronics Co., Ltd. https://shenzhenlk.en.alibaba.com/product/62074920029-811716276/4_Pin_Magnetic_Connector_4_Pin_Pogo_Pin_To_Usb_Cable_PCB_4Pin_Connector_Male_Female_Connector_Smartwatch.html
2. Hyte Technology Limited https://hytepro.en.alibaba.com/product/62327772156-812944918/4_pogo_pin_data_magnetic_pcb_connector_with_female_and_male.html
3. Hytepro Technologies Limited https://hyte.en.alibaba.com/product/1600089874345-805606376/Hytepro_positive_4pin_magnetic_charger_cable_connector_dc_pcb_adapter.html
4. Shenzhen QH Industrial Co., Ltd. https://mold-parts.en.alibaba.com/product/1600214253589-812290259/High_Quality_Pcb_Pogo_Pin_Usb_Male_Dc_4_pin_Magnetic_Charging_Cable_Automotive_Electrical_Connector.html
5. Dongguan Bofan Technology Co., Ltd. https://dgbofan.en.alibaba.com/product/60825989769-0/4_Pogo_Pin_Magnetic_Usb_Waterproof_3_0_Port_Connector_Micro_Usb_Waterproof.html
6. Dongguan Cfe Electronic Co., Ltd. https://cfconn.en.alibaba.com/product/60783675303-804434158/White_4pin_Magnetic_Pogo_Pin_Connector_Adapter_4p.html
7. Dongguan Access Star Electronic Co., Ltd. https://access-star.en.alibaba.com/product/60677449119-812371672/Braided_Magnet_Android_Magnetic_Charging_USB_Cable_POGO_cable.html

**Comment by maltfield** [comment]
One of the vendors above (Una Ou from Shenzhen QH Industrial Co., Ltd) understood my inquery and provided a couple images of a possible solution. It's not an adapter like the prototype, but I think this cable will meet our requirements

<img width="300" src="https://i.imgur.com/DlEervc.jpg" />

**Comment by maltfield** [comment]
Shenzhen QH Industrial Co., Ltd sent their catalog.

 * https://github.com/BusKill/usb-a-magnetic-breakaway/blob/master/supplier/shenzen_qh_industrial_co/productCatalogue_2020_rev5.pdf

And a `.stl` file for our customized cable as requested.

 * https://raw.githubusercontent.com/BusKill/usb-a-magnetic-breakaway/master/supplier/shenzen_qh_industrial_co/2021-05-24/una1.stl

I responded saying that the cable looks OK but the length is way off. And asking what the MOQ would be.

**Comment by maltfield** [comment]
QH fixed the .stl file's cable length and also the double-male-end so it's actually a proper extension cable. Updated .stl is here:

 * https://github.com/BusKill/usb-a-magnetic-breakaway/blob/master/supplier/shenzen_qh_industrial_co/2021-05-26/4Pin_2.54mmPH_runway_male_female_magnetic_connector_with_USB-Female_adapter.stp

Raster gimp .xcf files are here:
 * https://github.com/BusKill/usb-a-magnetic-breakaway/tree/master/digitalAssets/logo/2020_raster

**Comment by maltfield** [comment]
Per our conversation @goldfishlaser will try to convert the logo to an svg with inkscape and then teach me how to engrave it onto the overmold in the .stl using freecad.

**Comment by maltfield** [comment]
I was finally able to pocket the logo into the cable overmold!!

This commit has the freecad file with buskill logo "carved" into the overmold of the custom adapter housing the USB-A female receptacle.

I think the reason freecad kept figthing me was because of the way it handles imported .stp files or something. Anyway, I discovered the following process permitted me to pocket the logo into the overmold:

<img width="400" src="https://raw.githubusercontent.com/BusKill/usb-a-magnetic-breakaway/master/digitalAssets/cad/cable/cable_with_logo.20210603.jpg" />

  1. Import the logo in svg format

  2. Convert the logo from a draft to a sketch (Draft Workbench -> Convert bidirectionally between draft & sketch objectt) -- Do *not* combine all of the individual letters into one sketch, else you'll be unable to pocket it because the sketch's bodies are dijointed

  3. Create a new body at the root of the freecad file *outside* the .stp tree (yellow staircase/step icon)

  4. Click & drag the overmold to this new body

  5. Click & drag all the sketches of the logo's letters into the same body as the overmold

  6. Ctrl+click to slect all of the logo's letters. Click the "Data" tab, expand the "Position" field, and click +/- on the axis until the logo is position above the overmold (it doesn't matter how close it is, just fiddle with the two coordinates so the letters are centered atop the overmold.

  7. Double-click the body to activate it.

  8. One-by-one, click the sketches and choose Part Design -> Pocket. Figure out the right mm so it just carves into the surface without going through it. Do this again for each letter.

**Comment by maltfield** [comment]
I asked Shenzhen QH Industrial Co., Ltd if the size of the female connector was reasonable. She contacted the tools team and came back with this. It's larger, and seems much more practical

<p align="center"><img width="700" src="https://raw.githubusercontent.com/BusKill/usb-a-magnetic-breakaway/master/supplier/shenzen_qh_industrial_co/2021-06-10/buskill_custom_female_3d_screenshot.jpg" /></p>

 * https://github.com/BusKill/usb-a-magnetic-breakaway/blob/9cba65f5c64c256c2ebaba18489f21f92dc5df21/supplier/shenzen_qh_industrial_co/2021-06-10/4Pin_2.54mmPH_runway_male_female_magnetic_connector_with_USB-Female_adapter_20210609.stp

**Comment by maltfield** [comment]
I'm setting-aside the USB-A design for now since it's a higher barrier-of-entry, and we have most of the info needed to figure out how to achieve it.

The lowest barrier-of-entry is to just got USB-C, which might be the only practical option to achieve *before* I want to launch the crowdfunding campaign (if we get funded, then we'll have $ that could help to proceed with manufacturing the USB-A cable.)

To start, I wanted to find a complete list of manufacturers on alibaba of USB-C magnetic breakaways and some other min requirements.

So I searched for `usb magnetic` on alibaba and limited my query to only items with

	a. USB Type: TYPE-C
	b. Product Type: Ready to Ship
	c. Product Certification: FCC
	d. Product Certificatio CE
	e. Product Certification ROHS

And I got the following list of 19 vendors, sorted alphabetically by URL (which I can further refine in subsequent research)

1. https://atsound.en.alibaba.com/company_profile.html Shenzhen Auto Intelligence Technology Co., Ltd.
1. https://chargingcable.en.alibaba.com/company_profile.html Shenzhen Feixin Intelligent Co., Ltd.
1. https://eonline.en.alibaba.com/company_profile.html Shenzhen EONLINE Industrial Co., Ltd.
1. https://faman2.en.alibaba.com/company_profile.html Shenzhen Da Yuan Sheng Electronic Technology Co., Ltd.
1. https://feixinsmart.en.alibaba.com/company_profile.html Shenzhen Feixin Intelligence Co., Ltd.
1. https://focusestech.en.alibaba.com/company_profile.html Shenzhen Focuses Electronics Co., Ltd.
1. https://gzkallin.en.alibaba.com/company_profile.html Guangzhou Bewin Electronic Co., Ltd.
1. https://jmto.en.alibaba.com/company_profile.html Guangdong JiuMuTong Industry Co., Ltd.
1. https://logee.en.alibaba.com/company_profile.html Shenzhen Aovlex-Link Technology Co., Ltd.
1. https://newcase.en.alibaba.com/company_profile.html Guangzhou Veaqee Electronic Co., Ltd.
1. https://parbaytec.en.alibaba.com/company_profile.html Foshan Parbay Technology Co., Ltd.
1. https://szrewin.en.alibaba.com/company_profile.html Shenzhen Rewin Electronic Co., Ltd.	
1. https://sztyhtech.en.alibaba.com/company_profile.html Shenzhen Tongyinhai Precision Electronics Co., Ltd.
1. https://topkofficial.en.alibaba.com/company_profile.html Dongguan Chenxun Electronics Co., Ltd.
1. https://usams.en.alibaba.com/company_profile.html Shenzhen Usams Trading Co., Ltd.
1. https://usamsoriginal.en.alibaba.com/company_profile.html Shenzhen Youshengshi Technology Co., Ltd.
1. https://vothoon.en.alibaba.com/company_profile.html Shenzhen Cooltech Electronics Technology Co., Ltd.
1. https://xxd-cable.en.alibaba.com/company_profile.html Shenzhen Xin Xin Da Communication Technology Co., Ltd.
1. https://yfegroup.en.alibaba.com/company_profile.html Suzhou Yourfriend Electronic Co., Ltd.

**Comment by maltfield** [comment]
Of the list of alibaba vendors on the previous post, there are some providing a male-female USB-C magnetic breakaway adapter that wouldn't require a Frankenstein conglomeration including the female-female adapter.

1. https://eonline.en.alibaba.com/company_profile.html

**Comment by maltfield** [comment]
Yesterday I contacted the above 3x vendors on alibaba. The last two seem like small-time players, but the first one sent me a whole catalog page of their various USB magnetic adapters

<img width="600" src="https://raw.githubusercontent.com/BusKill/usb-a-magnetic-breakaway/2a981d0f270efb7306b24d460cec42bdf2eb508a/supplier/shenzhen_eonline_industrial_co/eonline_catalog_202106.jpg" />

**Comment by maltfield** [comment]
I'm still struggling to get the payment link from EONLINE.

Meanwhile, I should probably find the USB-C (male) to USB-A (female) 1m "extension cable" whoose male-end would plug into the above USB-C magnetic breakaway adapter and whose female receptacle would take-in the USB-A thumb drive.

I searched for options of 1m cables, and I found only a couple. I think it makes more sense to search for all the vendors that sell the cables and just ask if they can make it in 1m lengths. For this, I searched for "usb otg cable" and selected the "USB Type: TYPE-C" option and only "Seller Type: Assessed Supplier" and "Product Type: Ready to Ship". I sorted & `uniq`d the results, and here's the complete list:

1. https://4successful.en.alibaba.com/company_profile.html
1. https://7west.en.alibaba.com/company_profile.html
1. https://cantell.en.alibaba.com/company_profile.html
1. https://cnbloom.en.alibaba.com/company_profile.html
1. https://cnmagelei.en.alibaba.com/company_profile.html
1. https://cnwistar.en.alibaba.com/company_profile.html
1. https://dashengvytech.en.alibaba.com/company_profile.html
1. https://dgbofan.en.alibaba.com/company_profile.html
1. https://dgxunguang.en.alibaba.com/company_profile.html
1. https://doonjiey.en.alibaba.com/company_profile.html
1. https://eonline.en.alibaba.com/company_profile.html
1. https://googfit.en.alibaba.com/company_profile.html
1. https://guobuy.en.alibaba.com/company_profile.html
1. https://gzkallin.en.alibaba.com/company_profile.html
1. https://haiyijin.en.alibaba.com/company_profile.html
1. https://logee.en.alibaba.com/company_profile.html
1. https://magelei.en.alibaba.com/company_profile.html
1. https://opelu.en.alibaba.com/company_profile.html
1. https://oudakx.en.alibaba.com/company_profile.html
1. https://pogocharger.en.alibaba.com/company_profile.html
1. https://sanguanideatech.en.alibaba.com/company_profile.html
1. https://sbtool.en.alibaba.com/company_profile.html
1. https://suntc.en.alibaba.com/company_profile.html
1. https://szbst.en.alibaba.com/company_profile.html

**Comment by maltfield** [comment]
The following suppliers said they could make a USB-C male -> USB-A female OTG cable in 1 meter lengths:

| Vendor | MOQ | Price/Ea |
--- | --- | ---
|Shenzhen Sanguan Siyuan Technology Co., Ltd.| 300 | 1.58 |
| Shenzhen Sunning Tension Industrial Co., Ltd. | ? | 0.84USD |

**Comment by maltfield** [comment]
Shenzhen QH Industrial Co informed me that the first-sample-run of the custom BusKill magnetic breakaways had some atheistic defects, and they "still need to improve the mold for good tolerance and aesthestic quality."

<img width="400" src="https://raw.githubusercontent.com/BusKill/usb-a-magnetic-breakaway/master/supplier/shenzen_qh_industrial_co/2021-11-14/buskill_samples_001.jpg" />

**Comment by maltfield** [comment]
We were able to find all the suppliers we need and are now selling the manufactured injection-mold USB-A BusKill cables directly on our website and through Crowd Supply

 * https://buskill.in/buy

**Comment by goldfishlaser** [comment]
photos attached:

![cut open more](https://user-images.githubusercontent.com/597904/236359317-3d23eac5-787d-4699-a75d-d6242597a2d3.png)
![cut open](https://user-images.githubusercontent.com/597904/236359352-8d453d39-2dc5-4ec7-a29a-4d5b4073d2a8.png)
![the shell](https://user-images.githubusercontent.com/597904/236359510-2c82e5aa-0d37-480c-a5a8-baea20912dbe.png)

**Comment by goldfishlaser** [comment]
Additional photos

Cord

![image](https://user-images.githubusercontent.com/597904/236634645-3ec297c0-501b-4946-84e6-eef6d523d022.png)
No shielding nor drain wire. 

Other connectors insides 
![image](https://user-images.githubusercontent.com/597904/236634673-ee374f89-7ae6-4e2b-bc52-b56411425a18.png)
