### ISSUE TITLE
Alternative idea with Bluetooth dongle.

### ISSUE THREAD

**Issue by leoheck** [BusKill/usb-a-magnetic-breakaway#7]
I got an alternative idea. Instead of a USB device that breaks, what if a USB-Bluetooth dongle is used instead?

For instance, the user configures the app to check if the smartphone is in the defined range, otherwise it blocks the computer.

**Comment by maltfield** [comment]
@leoheck bluetooth-based solutions are numerous, but they're less secure and more fautly.

For more information, please [Q: But bluetooth...](https://docs.buskill.in/buskill-app/en/stable/faq.html#faq-bluetooth) in the project's FAQs 

 * https://docs.buskill.in/buskill-app/en/stable/faq.html#faq-bluetooth
